### ISSUE TITLE
Compiling issue with GCC 8

### ISSUE THREAD

**Issue by willgpaik** [frankyeh/DSI-Studio#32]
I was trying to build DSI Studio on Centos 7 with GCC 8.2.1. After I upgraded GCC from 7.3.1 to 8.2.1, compilation failed every time with error message like:
```
In file included from ../src/tipl/morphology/morphology.hpp:7,
                 from ../src/tipl/tipl.hpp:32,
                 from ../src/libs/vbc/vbc_database.h:5,
                 from ../src/mainwindow.h:6,
                 from ../src/main.cpp:9:
../src/tipl/numerical/basic_op.hpp: In instantiation of ‘void tipl::change_endian(type&) [with type = double]’:
../src/tipl/numerical/basic_op.hpp:974:22:   required from ‘void tipl::change_endian(datatype*, int) [with datatype = double]’
../src/tipl/io/dicom.hpp:218:90:   required from here
../src/tipl/numerical/basic_op.hpp:935:24: warning: comparison of integer expressions of different signedness: ‘char’ and ‘long unsigned int’ [-Wsign-compare]
     for (char i = 0; i < sizeof(type); ++i,--pdata)
                      ~~^~~~~~~~~~~~~~
../src/tipl/numerical/basic_op.hpp:936:17: warning: array subscript has type ‘char’ [-Wchar-subscripts]
         temp[i] = *pdata;
make: *** [Makefile:2502: main.o] Error 1
```
Each time, it failed at slightly different lines but I was unable to build it. Same issue happened on Fedora 28 with GCC 8.2.1. It is not a critical issue but I couldn't find the solution. Thanks!

**Comment by frankyeh** [comment]
Here it is a simple "type warning" if we compare any two different types of
integers.

It seems to me that the compiler was strictly set to halt if there is a
warning.

There is a way to silence those warning.

Best regards,
Frank

**Comment by willgpaik** [comment]
Hi Frank, I found an actual error message:
```
In file included from ../src/tipl/io/io.hpp:6,
                 from ../src/tipl/tipl.hpp:48,
                 from ../src/libs/vbc/vbc_database.h:5,
                 from ../src/mainwindow.h:6,
                 from ../src/main.cpp:9:
../src/tipl/io/nifti.hpp: In member function ‘const float* tipl::io::nifti_base<input_interface, output_interface>::get_transformation()’:
../src/tipl/io/nifti.hpp:729:28: error: cannot convert ‘double*’ to ‘const float*’ in return
         return nif_header2.srow_x;
                            ^~~~~~
```
It didn't happen when using GCC 7.3.1 though. It seems like "nif_header2.srow_x" is initialized as ``double`` inside the structure but returned as ``const float``.

**Comment by frankyeh** [comment]
Thank you for reporting this problem. I fixed it accordingly.
Frank

**Comment by willgpaik** [comment]
Thank you for the update. I encountered another error while compiling DSI Studio. Can you please take a look:
```
../src/tipl/vis/march_cube.hpp:443:57: error: 'class image_type::value_type' resolves to 'tipl::image<float, 3>::value_type' {aka 'float'}, which is is not a class type
             std::vector<typename ImageType::value_type> pixels;
                                                         ^~~~~~
../src/tipl/vis/march_cube.hpp:443:57: error: 'class image_type::value_type' resolves to 'tipl::image<float, 3>::value_type' {aka 'float'}, which is is not a class type
In file included from ../src/tipl/morphology/morphology.hpp:7,
                 from ../src/tipl/tipl.hpp:32,
                 from ../src/tracking/region/RegionModel.h:7,
                 from ../src/tracking/region/RegionModel.cpp:6:
../src/tipl/numerical/basic_op.hpp: In instantiation of 'void tipl::change_endian(type&) [with type = double]':
../src/tipl/numerical/basic_op.hpp:974:22:   required from 'void tipl::change_endian(datatype*, int) [with datatype = double]'
../src/tipl/io/dicom.hpp:226:90:   required from here
```

**Comment by frankyeh** [comment]
I tried a fix. Please check if it works now.
Frank

**Comment by willgpaik** [comment]
Frank, I'm still getting error message from the same line:
```
::march_cube(const ImageType&, typename ImageType::value_type) [with ImageType = tipl::image; VectorType = tipl::vector<3>; typename ImageType::value_type = unsigned char]':../src/tracking/region/RegionModel.cpp:98:73: required from here../src/tipl/vis/march_cube.hpp:443:57: error: 'class image_type::value_type' resolves to 'tipl::image

::value_type' {aka 'unsigned char'}, which is is not a class type std::vector
pixels; ^~~~~~../src/tipl/vis/march_cube.hpp:443:57: error: 'class image_type::value_type' resolves to 'tipl::image
```
Not sure why this only happens with newer version of GCC.

**Comment by frankyeh** [comment]
I really have no idea because the code seems to pass compiler on Windows
and Mac.

You may replace "typename ImageType::value_type" by "unsigned char" too see
if it suppress the error.

I could not think of other ways for the time being.
Frank

**Comment by willgpaik** [comment]
Hi Frank,

I can test it later
